### ISSUE TITLE
Percona class itself not imported in Foreman

### ISSUE THREAD

**Issue by Yamakasi** [vmindru/puppet-percona#2]
Hi,

Nice to see this module but in some way Foreman (1.21) doesn't import the percona class from init.pp itself.

The ones it imports are:

```
percona::install
percona::master
percona::params
percona::preinstall
percona::repo::yum
```

Any clue about this ?

Thanks for the good work!

Cheers,

Matt

**Comment by vmindru** [comment]
it's very late here and I am somehow tired  ... off the bat try to rename puppet module from `puppet-percona` to `percona`  not sure this will help though, i can try to look into this on Monday.

**Comment by Yamakasi** [comment]
Hi, no clue ? The docs look pretty straight forward but this is missing.

**Comment by Yamakasi** [comment]
@vmindru any idea ?
